model:
  boosting: "gbdt"
  learning_rate: 0.003
  max_depth: -1
  n_estimators: 700
  num_leaves: 10
features:
  features_to_normalize: ['RH_1', "RH_2", "RH_3", "RH_4", "RH_5", "RH_6", "RH_7", "RH_8", "RH_9", "RH_out"]
  raw_features: ['lights', 'T_out', 'Press_mm_hg', 'Windspeed', 'Visibility', 'Tdewpoint', 'T4','T5','T6','T7','T8', 'T9']
  optimization_features: ['T1', 'T2','T3']
  regression_feature: 'Appliances'
optimization:
  limit_temperature : [16,30]
  step : 0.1
